project:
  type: website
  output-dir: _site

website:
  title: ""
  site-url: https://torricallan.com.au
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: writing.qmd
        text: Writing
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
  page-footer:
    center: "Â© 2026 Torri Callan"

format:
  html:
    theme:
      light: custom.scss
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: false
    highlight-style: github
    html-math-method: katex
